# <center><font color="pink">K_FoldCrossValidation in Iris Dataset</font></center>

In [20]:
from sklearn import datasets
iris=datasets.load_iris()

In [21]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [33]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np


## Logistic Regression

In [53]:
l_scores=cross_val_score(LogisticRegression(max_iter=200),iris.data,iris.target)
l_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [54]:
np.average(l_scores)

0.9733333333333334

## Support Vector Machine

In [55]:
s_scores=cross_val_score(SVC(),iris.data,iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [56]:
np.average(s_scores)

0.9666666666666666

## Random Forest

In [59]:
r_scores=cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [60]:
np.average(r_scores)

0.96

## Decision Tree

In [40]:
d_scores=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [42]:
np.average(d_scores)

0.9666666666666668